apiVersion: apps/v1
kind: Deployment
metadata:
  name: bussines-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bussines-service
  template:
    metadata:
      labels:
        app: bussines-service
    spec:
      containers:
        - name: bussines-service
          image: bussines_service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: bussines-service
spec:
  selector:
    app: bussines-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
      nodePort: 30002
  type: NodePort
